pipeline:
  name: p1_remote
  identifier: p1_remote
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: var1
      type: String
      description: ""
      required: false
      value: <+input>.default(stable)
    - name: regex
      type: Number
      description: ""
      required: false
      value: "<+input>.default(1).regex(^(?:[0-9]|[0-1]\d|2[0-5])$)"
