pipeline:
  name: remote2
  identifier: remote2
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        identifier: custom1
        name: custom1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables:
                      - name: var1
                        type: String
                        value: <+input>
                      - name: var2
                        type: String
                        value: <+input>
                    outputVariables: []
                  timeout: <+input>
        tags: {}
