pipeline:
  name: remRecon
  identifier: remRecon
  projectIdentifier: naidusanity
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        identifier: custom1
        name: custom1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  identifier: ShellScript_1
                  type: ShellScript
                  name: ShellScript_1
                  spec:
                    onDelegate: true
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: exit 0
                    environmentVariables:
                      - name: var1
                        type: String
                        value: <+input>
                      - name: var2
                        type: String
                        value: <+input>
                    outputVariables: []
                  timeout: <+input>
              - step:
                  identifier: step1
                  name: step1
                  template:
                    templateRef: temStep
                    versionLabel: v1
                    templateInputs:
                      type: ShellScript
                      spec:
                        environmentVariables:
                          - name: var2
                            type: String
                            value: <+input>
                          - name: var1
                            type: String
                            value: <+input>
        tags: {}
